# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
 # Resolve script with node to allow for hoisting
 require Pod::Executable.execute_command('node', ['-p',
  "require.resolve(
      '#{script}',
       {paths: [process.argv[1]]},
    )", __dir__]).strip
 end

 node_require('react-native/scripts/react_native_pods.rb')
 node_require('react-native-permissions/scripts/setup.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
])


# Firebase requires static frameworks for proper module support
use_frameworks! :linkage => :static

target 'GasBooking' do
  config = use_native_modules!
  $RNFirebaseAsStaticFramework = true
  pod 'GoogleUtilities', :modular_headers => true
  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  pod 'react-native-maps', :path => '../node_modules/react-native-maps'
  pod 'GoogleMaps'
  
  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end
end
